# Generated by Django 3.1.11 on 2021-05-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='author',
        ),
    ]
