# Generated by Django 3.1.11 on 2021-05-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_game_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.CharField(default='', max_length=13),
        ),
    ]
