# Generated by Django 3.1.11 on 2021-05-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_remove_game_aa'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('T', 'Toplay'), ('P', 'Progressing'), ('F', 'Finished')], default='T', max_length=1),
        ),
    ]
